#!/usr/bin/env python
import heapq
import sys


def main():
    nums = [int(x) for x in sys.argv[1:]]
    heap_nums = nums[:]
    heapq.heapify(heap_nums)
    
    if heap_nums == nums:
        print 'True'
    else:
        print 'False'


if __name__ == '__main__':
    sys.exit(main())
